version: '3.8'

services:
  api:
    image: 561903439208.dkr.ecr.sa-east-1.amazonaws.com/github-actions-test:latest
    container_name: nestjs_cine_api
    restart: always
    ports:
      - '3000:3000'
    environment:
      DB_HOST: cine-db.cluster-c1wsoe4o4szl.sa-east-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: myapp_dev
